package utils

import models.User

object SetupData {

  val setupData = Seq(
    User(1,
         "Waikar",
         "Chaitanya",
         "male",
         "cw@yahoo.com",
         subscribedNewsletter = true),
    User(2,
         "Turner",
         "Tom",
         "male",
         "tom.turner@provider.de",
         subscribedNewsletter = true),
    User(4,
         "Doe",
         "John",
         "male",
         "jon.doe@test-mailing.com",
         subscribedNewsletter = true),
    User(5,
         "Smith",
         "Karen",
         "female",
         "k-smith@something.de",
         subscribedNewsletter = false),
    User(6,
         "Turner",
         "Maria",
         "female",
         "maTur@somewhere.com",
         subscribedNewsletter = true),
    User(7,
         "Murphy",
         "Donald",
         "male",
         "DoMu@provider.de",
         subscribedNewsletter = false),
    User(8,
         "Cooper",
         "Anne",
         "female",
         "a.cooper@test-mail.com",
         subscribedNewsletter = true),
    User(9,
         "Goldsmith",
         "Peter",
         "male",
         "p-goldsmith@provider.de",
         subscribedNewsletter = true),
    User(10,
         "Smith",
         "Collin",
         "male",
         "collin-smith@test-mailing.com",
         subscribedNewsletter = true),
    User(11,
         "Walker",
         "Karen",
         "female",
         "karen-walker@something.de",
         subscribedNewsletter = true),
    User(12,
         "Coco",
         "Scrapy",
         "female",
         "coco-scrapy@somewhere.com",
         subscribedNewsletter = false),
    User(13,
         "Doe",
         "Craig",
         "male",
         "DoeCraig@provider.de",
         subscribedNewsletter = true),
    User(15,
         "McGillan",
         "Johnathan",
         "male",
         "jmc@test-mailing.com",
         subscribedNewsletter = true),
    User(16,
         "Wright",
         "Samy",
         "female",
         "s.wright@something.de",
         subscribedNewsletter = false),
    User(17,
         "McCallan",
         "Maria",
         "female",
         "marmccal@somewhere.com",
         subscribedNewsletter = true),
    User(18,
         "Allen",
         "Joe",
         "male",
         "joe-allen@provider.de",
         subscribedNewsletter = true),
    User(19,
         "Davis",
         "Caroline",
         "female",
         "c-davis@test-mail.com",
         subscribedNewsletter = true),
    User(20,
         "Kerry",
         "Craig",
         "male",
         "craigKerryh@provider.de",
         subscribedNewsletter = true),
    User(21,
         "Williams",
         "Gerard",
         "male",
         "williams-gerard@test-mailing.com",
         subscribedNewsletter = true),
    User(22,
         "Miller",
         "Kirsten",
         "female",
         "kmiller@something.de",
         subscribedNewsletter = true),
    User(23,
         "Brown",
         "Kathy",
         "female",
         "brown.kathy@somewhere.com",
         subscribedNewsletter = false),
    User(24,
         "Jones",
         "Thomas",
         "male",
         "tom-jones@provider.de",
         subscribedNewsletter = true),
    User(25,
         "Wright",
         "Carolina",
         "female",
         "caro-wright@test-mail.com",
         subscribedNewsletter = true)
  )

}
